version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      # your Flask env, DB URLs, etc.
      FLASK_ENV: production

  frontend:
    build:
      context: ./value-core-frontend
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # point React at the backend service by its Docker Compose name
      REACT_APP_API_URL: http://backend:5000

# all services share this default network, so "frontend" can call "http://backend:5000"
